- hosts: towers
  become: yes
  tasks:
  - name: Download private key
    copy: 
      src: id_rsa 
      dest: /var/lib/awx/.ssh/id_rsa
      mode: 0600
      owner: awx
      group: awx
  - name: Create ssh_config file for connecting to the jumpbox
    blockinfile:
      path: /var/lib/awx/.ssh/aws_ssh_config
      create: yes
      owner: awx
      group: awx
      mode: 0640
      block: |
        Host {{ jump_host_name }}
        Hostname {{ jump_host_name }}
        IdentityFile /var/lib/awx/.ssh/id_rsa
        ForwardAgent yes
        User cloud-user
        ControlMaster auto
        ControlPath /tmp/%h-%r
        ControlPersist 5m
        StrictHostKeyChecking no

  - name: Add ssh_args in ansible.cfg to point to the AWX user's SSH config
    lineinfile:
      path: /etc/ansible/ansible.cfg
      insertafter: '^#ssh_args '
      line: 'ssh_args = -F /var/lib/awx/.ssh/aws_ssh_config'
  - name: Disable PRoot
    lineinfile:
      path: /etc/tower/settings.py
      line: 'AWX_PROOT_ENABLED = False'
    notify:
      - restart tower
  handlers:
    - name: restart tower
      command: 'ansible-tower-service restart'
