---
- name: Configure Database Servers
  hosts: tag_AnsibleGroup_appdbs
  roles:
  - enable_repos
  - configure_postgres
  become: true
  become_user: root

- name: Configure Application Servers
  hosts: tag_AnsibleGroup_apps
  roles:
  - enable_repos
  - configure_tomcat
  - install_apache
  - deploy_webapp
  become: true
  become_user: root

- name: Configure Frontend Servers
  hosts: tag_AnsibleGroup_frontends
  roles:
  - enable_repos
  - configure_haproxy
  become: true
  become_user: root
